# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: sonicbld

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-bookworm
      swss_common_artifact_name: sonic-swss-common
      artifact_name: sonic-stp

- stage: BuildArm
  dependsOn: []
  jobs:
  - template: .azure-pipelines/build-template.yml
    condition: false # build error, skip currently
    parameters:
      arch: armhf
      timeout: 180
      pool: sonicbld-armhf
      sonic_slave: sonic-slave-bookworm-armhf
      swss_common_artifact_name: sonic-swss-common.armhf
      artifact_name: sonic-stp.armhf

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 180
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-bookworm-arm64
      swss_common_artifact_name: sonic-swss-common.arm64
      artifact_name: sonic-stp.arm64
